SELECT * FROM CUSTOMERS;

SELECT FIRSTNAME,LASTNAME FROM CUSTOMERS;

SELECT FIRSTNAME,LASTNAME, CUST_ID,PHONE FROM CUSTOMERS;


SELECT * FROM CUSTOMERS WHERE CUST_ID>1006;

SELECT * FROM CUSTOMERS WHERE CUST_ID
BETWEEN 1010 AND 1020;

SELECT * FROM CUSTOMERS WHERE DOB
BETWEEN "1999-01-01" AND "1999-12-31";

SELECT * FROM CUSTOMERS
WHERE FIRSTNAME LIKE "%A";